# © 2024 INRAE
# SPDX-FileContributor: Marcellino Palerme <marcellino.palerme@inrae.fr>
#
# SPDX-License-Identifier: MIT

name: publish

on:
  pull_request:
    branches: 'main'

permissions: 
  contents: write
  pull-requests: write
  checks: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - name: set lower case owner name
      id: set_owner_lc
      run: |
        echo "OWNER_LC=${OWNER,,}" >> "$GITHUB_OUTPUT"
      env:
        OWNER: '${{ github.repository_owner }}'
    - name: Build and publish Docker image with multiple tags
      uses: VaultVulp/gp-docker-action@1.6.0
      env:
        OWNER: ${{ steps.set_owner_lc.outputs.OWNER_LC }}
      with:
        github-token: ${{secrets.MY_TOKEN}} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: service-p2m2tools-api # Provide Docker image name
        additional-image-tags: 1.7.1 # two additional tags for an image
        dockerfile: DockerfileQuay # Provide Dockerfile path
        custom-args: --build-arg=TEAM=${{ env.OWNER }} # Provide custom arguments for the Docker build